### ISSUE TITLE
C# Track Courses to be Completed

### ISSUE THREAD

**Issue by charlessims** [charlessims/Treehouse#2]
## TODO

*Courses left to complete the Treehouse C# Track*

* [ ] Using GitHub with Visual Studio
* [ ] Debugging in Visual Studio
* [ ] Becoming a Visual Studio Power User

:tada: :ok_man:
